// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8qmlSKBCrhYxpttwX_KmsiPJg5hncqts',
    appId: '1:589044020422:android:a01cf9d702d810fcfad3c7',
    messagingSenderId: '589044020422',
    projectId: 'pushnotifications-92524',
    storageBucket: 'pushnotifications-92524.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWUGQtP8M5z7QZQi7Wqw6sxGT69jIrP4k',
    appId: '1:589044020422:ios:0b2c1a301043c5c0fad3c7',
    messagingSenderId: '589044020422',
    projectId: 'pushnotifications-92524',
    storageBucket: 'pushnotifications-92524.firebasestorage.app',
    iosBundleId: 'com.example.notificationsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpuSH8ubdCOZNRfeU4x22SdTcNTZIMAvM',
    appId: '1:589044020422:web:9c7faefaf42bd23bfad3c7',
    messagingSenderId: '589044020422',
    projectId: 'pushnotifications-92524',
    authDomain: 'pushnotifications-92524.firebaseapp.com',
    storageBucket: 'pushnotifications-92524.firebasestorage.app',
  );
}
